### ISSUE TITLE
State of the OSv patches?

### ISSUE THREAD

**Issue by paulreimer** [OtoloNetworks/otp-osv#1]
I'm interested in using the `rebar3_osv` plugin, and this fork is required. I'm wondering about reviewing the patches, and if they might eventually be accepted by upstream?

Ideally the patches could be isolated into small + atomic git commits on top of the vanilla OTP sources.

As well, in general I'm wondering about how this repo and the patches would be maintained over time? (not expecting any sort of commitment, just wondering about the future)

**Comment by rickpayne** [comment]
We're mostly using the patches from the GRiSP project which has similar issues when running the BEAM on top or rtems. Its on my list to look at whether we can merge with rebar3_grisp, which has the advantage of building the OTP release as required, at which point this repo would not be required.
Not sure when I'll get chance though.

**Comment by paulreimer** [comment]
Sounds good! You say "mostly", is there some architecture-specific / x86 patching, on top of their patches?

GRiSP is now on my radar, thanks for mentioning that. Seems even closer to the metal than Nerves (or this project). Still, I'm interested in EC2, so I think your `rebar3_osv` plugin should be the best way to go for now.

**Comment by rickpayne** [comment]
You can see the changes [here](https://github.com/erlang/otp/compare/master...OtoloNetworks:OTP-20.0.5-OSv), for example. The main issue being the lack of fork and exec, which means epmd has to run in a thread (or use the erlang epmd that Peer did), and some of the system applications won't run without ports (which require fork+exec, so won't work). Also HIPE won't work as that does not work with PIE code unfortunately.

**Comment by paulreimer** [comment]
Perfect, that solves it! Thanks for that; it's a lot smaller of a diff than I was expecting (that's good news).

Bummer about HiPE.

Do you/have you used this in production (or heavy use of any kind)?

**Comment by rickpayne** [comment]
Yes, we're running 2 different internet facing erlang applications in production on servers, on top of OSv
