### ISSUE TITLE
OpenSSL Version Used / Required?

### ISSUE THREAD

**Issue by paulreimer** [OtoloNetworks/otp-osv#2]
When compiling a custom OSv image (from recent `master` on their repo), I seem to need a 1.0.x series to be compatible with this repo. (Ultimately at runtime it seems to check for the `SSLeay` symbol which is no longer exported in OpenSSL 1.1. I'm doing some extra hoops with the included `crypto.so` here to even be able to find a `libcrypto.so.1.0.0` since that's what my system calls it.)

Does that seem correct? What version of OpenSSL / `osv` are you using when you build these OTP libraries?

**Comment by rickpayne** [comment]
I'll try and update this soon. We are usually building our own OTP release...

**Comment by rickpayne** [comment]
I've updated this repo now to a much more recent OTP-23.0.1, which should help you. Re-open if you need more help...

**Comment by paulreimer** [comment]
Thank you! This is great. I'm able to use my system erlang + openSSL without patches and at the latest version. I'm also now able to use your provided `osv.img` rather than building my own. I'm just pointing directly at `master` for now.
